name = "Talking Room Vanilla+"
author = "VulgarBear"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "874b05eaad7a37ac6bfe1b1b80a3656cb059cf3e44db47525b97bb9ecc448270"

[versions]
fabric = "0.14.7"
minecraft = "1.19"
